package civwiki.dialogmw.client;

import java.util.Map;

/**
 * Inverse of the sprite mapping generated by
 * <a href="https://github.com/indyteo/MaterialSpritesGenerator">MaterialSpritesGenerator</a>
 * (release 1.21.11, {@code MaterialSprites.java}). It maps every atlas-sprite
 * key that is <em>not</em> a plain {@code minecraft:item/...} or
 * {@code minecraft:block/...} texture back to the item id the material stands
 * for, so the wiki copy can emit a real {@code {{ItemSprite|…}}} instead of a
 * garbage dashed path. Keys are the sprite identifiers as sent over the wire;
 * values are the wiki's dashed item ids.
 *
 * <p>Regenerate this file from the upstream release (same procedure as the
 * current content: filter {@code SPRITES.put(Material.X, sprite(...))} lines
 * whose sprite key is not {@code minecraft:item/} or {@code minecraft:block/},
 * and emit {@code lowercase-material-name} with {@code _} replaced by
 * {@code -}). Entries that share a sprite (wall and non-wall banners) map to
 * the same item id on purpose.</p>
 */
public final class MaterialSprites {

	/** Atlas-sprite key -> item id, for sprites outside minecraft:item and minecraft:block. */
	private static final Map<String, String> ITEM_BY_SPRITE = Map.ofEntries(
		Map.entry("minecraft:black_banner", "black-banner"),
		Map.entry("minecraft:blue_banner", "blue-banner"),
		Map.entry("minecraft:brown_banner", "brown-banner"),
		Map.entry("minecraft:bubble", "bubble-column"),
		Map.entry("minecraft:container/slot/shield", "shield"),
		Map.entry("minecraft:cyan_banner", "cyan-banner"),
		Map.entry("minecraft:entity/decorated_pot/danger_pottery_pattern", "decorated-pot"),
		Map.entry("minecraft:gray_banner", "gray-banner"),
		Map.entry("minecraft:green_banner", "green-banner"),
		Map.entry("minecraft:light_blue_banner", "light-blue-banner"),
		Map.entry("minecraft:light_gray_banner", "light-gray-banner"),
		Map.entry("minecraft:lime_banner", "lime-banner"),
		Map.entry("minecraft:magenta_banner", "magenta-banner"),
		Map.entry("minecraft:orange_banner", "orange-banner"),
		Map.entry("minecraft:pink_banner", "pink-banner"),
		Map.entry("minecraft:purple_banner", "purple-banner"),
		Map.entry("minecraft:red_banner", "red-banner"),
		Map.entry("minecraft:white_banner", "white-banner"),
		Map.entry("minecraft:yellow_banner", "yellow-banner")
	);

	private MaterialSprites() {
	}

	/** Returns the item id (wiki form) for a sprite key, or null when not a known material sprite. */
	public static String itemId(String spriteKey) {
		return ITEM_BY_SPRITE.get(spriteKey);
	}
}